### ISSUE TITLE
Plugin crashes when breakpoints are hit during debug

### ISSUE THREAD

**Issue by iranicus** [karatelabs/karate-intellij-plugin#19]
IntelliJ version: 2022.1.4 Ultimate
Plugin version: 1.5.0.196
Java version: 17.0.4 temurin
OS: Mac Monterey v12.2
Node version: 15.0.0
Karate version: 1.2.0

Whenever I try to debug a .feature file using breakpoints as soon as the running code hits it the plugin crashes with the following error:

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'value' of com/intellij/xdebugger/impl/ui/tree/nodes/XValueNodeImpl.setPresentation must not be null
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.$$$reportNull$$$0(XValueNodeImpl.java)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.setPresentation(XValueNodeImpl.java)
	at io.karatelabs.intellij.debug.KarateVariableValue.computePresentation(KarateVariableValue.java:28)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueNodeImpl.<init>(XValueNodeImpl.java:62)
	at com.intellij.xdebugger.impl.ui.tree.nodes.XValueContainerNode.lambda$addChildren$0(XValueContainerNode.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

The debugger of the IDE is also constantly showing 'Collecting data...'
Having checked the console the debug.DapServer is started on port 55763 with it shutting down fine at the end of the scenario I am trying to debug.
The breakpoint itself was on the following line:

```
    * def commitMetadataListAuthor = karate.jsonPath(response, "$.content[0:4].changes[*]..commitMetadata.author")
```
The goal being so I could figure out the value of this in the debugger without having to print it out, when the test finished I can confirm a value is assigned to this variable in case the mentioned not null error is about that. Or perhaps there is some incompatibility when jsonPath is being used?

**Comment by ptrthomas** [comment]
@iranicus we will look into this asap. by any chance would you be able to provide a feature ([better still a full maven project](https://github.com/karatelabs/karate/wiki/How-to-Submit-an-Issue)) where we can replicate this issue?

**Comment by iranicus** [comment]
> @iranicus we will look into this asap. by any chance would you be able to provide a feature ([better still a full maven project](https://github.com/karatelabs/karate/wiki/How-to-Submit-an-Issue)) where we can replicate this issue?

Unfortunately it is sensitive code so I can't provide the exact maven project, I will try put a dummy project together though

**Comment by iranicus** [comment]
I have created a sample application with the .feature file and the single scenario the problem was encountered with. It is not a working application but hopefully from the way the feature file is written and dependencies used it will help.

[demo-karate-debug.zip](https://github.com/karatelabs/karate-intellij-plugin/files/9823389/demo-karate-debug.zip)

**Comment by jansorg** [comment]
This should be fixed with the next update. Please reopen if you're still seeing this bug. Thanks!
