### ISSUE TITLE
IntelliJ IDEA 2023.2 RC (232.8660.142) freezes on startup with Karate plug-in installed

### ISSUE THREAD

**Issue by CrazyCoder** [karatelabs/karate-intellij-plugin#33]
Reported by a user to JetBrains support:

```
"Indexing" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
	at io.karatelabs.intellij.lang.karate.psi._KarateLexerGen.advance(_KarateLexerGen.java:874)
	at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:93)
	at com.intellij.lexer.FlexAdapter.getState(FlexAdapter.java:46)
	at com.intellij.lexer.LookAheadLexer.doLookAhead(LookAheadLexer.java:68)
	at com.intellij.lexer.LookAheadLexer.advance(LookAheadLexer.java:62)
	at com.intellij.lexer.MergingLexerAdapterBase.locateToken(MergingLexerAdapterBase.java:79)
	at com.intellij.lexer.MergingLexerAdapterBase.getTokenType(MergingLexerAdapterBase.java:48)
	at com.intellij.lang.cacheBuilder.DefaultWordsScanner.processWords(DefaultWordsScanner.java:106)
	at com.intellij.psi.impl.cache.impl.id.ScanningIdIndexer.map(ScanningIdIndexer.java:25)
	at com.intellij.psi.impl.cache.impl.id.ScanningIdIndexer.map(ScanningIdIndexer.java:15)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$2.map(IdIndex.java:98)
	at com.intellij.psi.impl.cache.impl.id.IdIndex$2.map(IdIndex.java:69)
	at com.intellij.util.indexing.CompositeDataIndexer.map(CompositeDataIndexer.java:55)
	at com.intellij.util.indexing.CompositeDataIndexer.map(CompositeDataIndexer.java:19)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapByIndexer(MapReduceIndex.java:313)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:304)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:162)
	at com.intellij.util.indexing.impl.storage.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:39)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInputAndPrepareUpdate(MapReduceIndex.java:249)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.updateBaseIndex(CompositeInvertedIndexBase.java:294)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:64)
	at com.intellij.indexing.composite.CompositeInvertedIndexBase.mapInputAndPrepareUpdate(CompositeInvertedIndexBase.java:30)
	at com.intellij.util.indexing.FileBasedIndexImpl.createSingleIndexValueApplier(FileBasedIndexImpl.java:1611)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$25(FileBasedIndexImpl.java:1480)
	at com.intellij.util.indexing.FileBasedIndexImpl$$Lambda$8585/0x000000080345b788.run(Unknown Source)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyWithProvidedValueIn(FileTypeManagerImpl.java:676)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1432)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1405)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexOneFileOfJob$4(IndexUpdateRunner.java:322)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner$$Lambda$8584/0x000000080345b538.call(Unknown Source)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:832)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:864)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:602)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$4(NonBlockingReadActionImpl.java:565)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission$$Lambda$2030/0x0000000801519ea8.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$$Lambda$2031/0x000000080151a0f8.run(Unknown Source)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:133)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$$Lambda$2033/0x000000080151a598.compute(Unknown Source)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:71)
	at com.intellij.openapi.progress.ProgressManager$$Lambda$1470/0x000000080113ea88.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1436/0x0000000801119520.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$1437/0x0000000801119770.compute(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:76)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:565)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.executeSynchronously(NonBlockingReadActionImpl.java:492)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.executeSynchronously(NonBlockingReadActionImpl.java:222)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexOneFileOfJob(IndexUpdateRunner.java:326)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$indexJobsFairly$3(IndexUpdateRunner.java:248)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner$$Lambda$8568/0x00000008034586d0.run(Unknown Source)
	at com.intellij.openapi.progress.impl.ProgressSuspender.executeNonSuspendableSection(ProgressSuspender.java:89)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.indexJobsFairly(IndexUpdateRunner.java:251)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner.lambda$doIndexFiles$2(IndexUpdateRunner.java:182)
	at com.intellij.util.indexing.contentQueue.IndexUpdateRunner$$Lambda$8566/0x0000000803458480.run(Unknown Source)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:24)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1$$Lambda$744/0x000000080088bbc8.run(Unknown Source)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.7/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base@17.0.7/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base@17.0.7/java.security.AccessController.executePrivileged(AccessController.java:776)
	at java.base@17.0.7/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base@17.0.7/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
```

Full dump: https://pastebin.com/yP22idiv

If you need help from JetBrains team, please file a request at https://youtrack.jetbrains.com/newIssue?project=IDEA

**Comment by ptrthomas** [comment]
@jansorg can you advise ?

**Comment by jansorg** [comment]
Thanks for reporting and providing the stack dump!

The AWT event queue thread is processing the close of the current project:
```
        at com.intellij.configurationStore.SaveAndSyncHandlerImpl.saveSettingsUnderModalProgress(SaveAndSyncHandlerImpl.kt:265)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.kt:370)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject$default(ProjectManagerImpl.kt:316)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.kt:416)
	at com.intellij.ide.actions.CloseProjectsActionBase.actionPerformed(CloseProjectsActionBase.kt:26)
```

It's launching a WriteAction and is waiting for ReadActions to finish.
Even though the KarateLexer is currently processing a file (as part of the indexing), it's unclear if it's the cause of the freeze or if it's working as intended and the dump was just taken at a moment when it was processing a .feature file.

AFAIK, the problems view is also executing a read action:
```

"Alarm Pool" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: TIMED_WAITING
 on com.intellij.openapi.application.impl.ReadMostlyRWLock@3c753be7
	at java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method)
	at java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.waitABit(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.startRead(ReadMostlyRWLock.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:921)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:76)
	at com.intellij.analysis.problemsView.toolWindow.HighlightingPanel.updateStatus(HighlightingPanel.kt:150)
```

I checked `KarateLexer` and couldn't spot an obvious bug.
Even if Karate is the culprit of this freeze, we're unable to fix it without the content of the indexed .feature file. AFAIK this file is unavailable.

**Comment by ljchen1** [comment]
>  Even though the KarateLexer is currently processing a file (as part of the indexing), it's unclear if it's the cause of the freeze or if it's working as intended and the dump was just taken at a moment when it was processing a .feature file.

I have attached all thread dump files here. In some thread dumps, you can see it stuck in Karate related code for more than 30 seconds. Some are near 100 seconds.
[IntelliJIdea2023.zip](https://github.com/karatelabs/karate-intellij-plugin/files/12179390/IntelliJIdea2023.zip)

>  Even if Karate is the culprit of this freeze, we're unable to fix it without the content of the indexed .feature file. AFAIK this file is unavailable.

We will ask the user about it. If we can get it, we will share it here.

**Comment by jansorg** [comment]
Thanks! I've found and fixed a cause of an endless lexer loop. It'll be published ASAP.

**Comment by ptrthomas** [comment]
new version 1.7.6.356-232 has been approved and is available: https://plugins.jetbrains.com/plugin/19232-karate/versions
